version: "3.8"

services:
  db:
    volumes:
      - ecommerce-analyzer-db-dev:/var/lib/postgresql/data/pgdata
    env_file:
      - env/dev.env

  pgadmin:
    env_file:
      - env/dev.env

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/dev.env

networks:
  ecommerce-analyzer-network:
    external: false

volumes:
  ecommerce-analyzer-db-dev:
